#!/data/data/com.termux/files/usr/bin/bash
# Spotify-Play-Pause — Toggle play/pause via Android media key broadcast.
am broadcast -a android.intent.action.MEDIA_BUTTON --ei "android.intent.extra.KEY_EVENT" 85 > /dev/null 2>&1
am broadcast -a android.intent.action.MEDIA_BUTTON --ei "android.intent.extra.KEY_EVENT" 85 --ez "EXTRA_DOWN" false > /dev/null 2>&1
termux-vibrate -d 80
